#!/usr/bin/env python3
"""Generate the committed OpenAPI 3.1 contract from the FastAPI application."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _configure_imports(root: Path) -> None:
    """Import the API without needing runtime services or production secrets."""
    os.environ["ENVIRONMENT"] = "development"
    os.environ["USE_AZURE_KEYVAULT"] = "false"
    os.environ.setdefault("SECRET_KEY", "openapi-contract-generation-only")
    api_root = root / "apps" / "api"
    sys.path.insert(0, str(api_root))
    for package in sorted((root / "packages").glob("*/src")):
        sys.path.insert(0, str(package))


def schema(root: Path) -> dict[str, Any]:
    _configure_imports(root)
    from app.main import app  # Imported after deterministic bootstrap.

    document = app.openapi()
    document["openapi"] = "3.1.0"
    document.setdefault("info", {})["description"] = (
        "Generated from the Agent Builder FastAPI application. "
        "Do not edit this file by hand; run scripts/generate_openapi.py."
    )
    return document


def encoded(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path, default=ROOT / "docs/api/openapi.json")
    parser.add_argument("--check", action="store_true", help="fail if the committed contract is stale")
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    document = schema(root)
    content = encoded(document)

    if args.check:
        actual = output.read_text(encoding="utf-8") if output.is_file() else ""
        if actual != content:
            raise SystemExit(
                f"OpenAPI contract is stale: regenerate with {Path(__file__).relative_to(root)} --output {output.relative_to(root)}"
            )
        print(f"OpenAPI contract is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Generated OpenAPI 3.1 contract with {len(document.get('paths', {}))} paths: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
